### ISSUE TITLE
Update install script for Ubuntu 18.04?

### ISSUE THREAD

**Issue by ghost** [kyle95wm/CoWFC#4]
What the title said.
I put this in the issues section in here because there's no issues section for the installer script.
Thanks

**Comment by kyle95wm** [comment]
Updating to Ubuntu 18.04 maybe sometime down the road once I can confirm that PHP 7.1, MySQL Server, Python 2.7, Apache and DNSMasq are all available on the standard repositories and work as intended. There is currently no time-frame for this.

**Comment by kyle95wm** [comment]
Closing this issue now since the installer repo now has issues enabled.
